name: ${name}
description: ${description}
version: ${version}
author: ${author}
website: ${url}
main: com.minekube.connect.SpigotPlugin
api-version: 1.13
folia-supported: false # TODO support folia
softdepend: [ProtocolSupport]