name: ${project.name}
description: ${project.description}
version: ${project.version}
author: ${project.organization.name}
website: ${project.url}
main: org.geysermc.floodgate.BukkitPlugin
commands:
    linkaccount:
        description: Link your Java and Bedrock accounts
        usage: /linkaccount [code]
        permission: floodgate.linkaccount
        permission-message: You don't have the floodgate.linkaccount permission.
    unlinkaccount:
        description: Unlink your Java account from your Bedrock account
        usage: /unlinkaccount
        permission: floodgate.unlinkaccount
        permission-message: You don't have the floodgate.unlinkaccount permission.
permissions:
    floodgate.linkaccount:
        description: Allows players to link their Bedrock and Java accounts
        default: true
    floodgate.unlinkaccount:
        description: Allows players to unlink their Bedrock and Java accounts
        default: true
