# The endpoint name of this server/proxy instance registered on startup with the Connect network.
# Default is a random string. Uncomment to specify your own endpoint name.
#endpoint:

# The default locale for Connect. By default, Connect uses the system locale
#default-locale: en_US

# bStats is a stat tracker that is entirely anonymous and tracks only basic information
# about Connect, such as how many people are online, how many servers are using Connect,
# what OS is being used, etc. You can learn more about bStats here: https://bstats.org/.
metrics:
  # If metrics should be disabled.
  disabled: false
  # The unique id that should be consistent for a server/proxy.
  id: ${metrics.id}

# Do not change this
config-version: 1
