# The endpoint name of this server/proxy instance registered on startup with the Connect network.
# Default is a random string. Uncomment to specify your own endpoint name.
#endpoint:

# The default locale for Floodgate. By default, Floodgate uses the system locale
#default-locale: en_US

# Do not change this
config-version: 1
