# The endpoint name of this server/proxy instance registered on startup with the Connect network.
# Default is a random string. You can change it to a custom endpoint name.
endpoint: ${endpoint}

# This setting is only relevant if you want to allow cracked players to join.
# If left blank, the correct mode will be securely detected automatically.
allow-offline-mode-players: false

# The default locale for Connect. By default, Connect uses the system locale
#default-locale: en_US

# Super endpoints are authorized to control this endpoint via Connect API.
# e.g. disconnect players from this endpoint, send messages to players, etc.
#
# You can add as many super endpoint names as you want.
#super-endpoints:
#  - pvp-endpoint
#  - someones-hub

# bStats is a stat tracker that is entirely anonymous and tracks only basic information
# about Connect, such as how many people are online, how many servers are using Connect,
# what OS is being used, etc. You can learn more about bStats here: https://bstats.org/.
metrics:
  # If metrics should be disabled.
  disabled: false
  # The unique id that should be consistent for a server/proxy.
  uuid: ${metrics.uuid}

# Do not change this
config-version: 1
