name: Publish
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 21

      - name: Build Floodgate-Modded
        run: ./gradlew build

      - name: Publish to Modrinth
        if: ${{ success() && github.repository == 'GeyserMC/Floodgate-Modded' && github.ref_name == 'master' }}
        uses: gradle/gradle-build-action@3bfe3a46584a206fb8361cdedd0647b0c4204232
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: modrinth
          gradle-home-cache-cleanup: true

      - name: Archive Artifacts
        uses: GeyserMC/actions/upload-multi-artifact@master
        if: success()
        with:
          artifacts: |
            Floodgate-Fabric:fabric/build/libs/floodgate-fabric.jar
            Floodgate-NeoForge:neoforge/build/libs/floodgate-neoforge.jar
