name: Publish
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
      - uses: actions/setup-java@4075bfc1b51bf22876335ae1cd589602d60d8758
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Publish to Modrinth
        uses: gradle/gradle-build-action@3bfe3a46584a206fb8361cdedd0647b0c4204232
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: modrinth
          gradle-home-cache-cleanup: true
      - name: Archive Artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        if: success()
        with:
          name: Floodgate Fabric
          path: build/libs/floodgate-fabric.jar
          if-no-files-found: error